// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import { wailsapp } from "../models";

export function AddLanguage(arg1: Record<string, any>): Promise<wailsapp.ConfigResult>;

export function AddRuntime(arg1: Record<string, any>): Promise<wailsapp.ConfigResult>;

export function AddTool(arg1: Record<string, any>): Promise<wailsapp.ConfigResult>;

export function Compress(arg1: wailsapp.FormatRequest): Promise<wailsapp.FormatResult>;

export function DeleteLanguage(arg1: string): Promise<wailsapp.ConfigResult>;

export function DeleteRuntime(arg1: string): Promise<wailsapp.ConfigResult>;

export function DeleteTool(arg1: string): Promise<wailsapp.ConfigResult>;

export function Detect(arg1: string): Promise<wailsapp.DetectResult>;

export function Format(arg1: wailsapp.FormatRequest): Promise<wailsapp.FormatResult>;

export function GetBinaries(): Promise<wailsapp.BinListResult>;

export function GetConfig(): Promise<wailsapp.ConfigResult>;

export function GetLanguages(): Promise<wailsapp.LanguagesResult>;

export function GetStatus(): Promise<wailsapp.StatusResult>;

export function Highlight(arg1: wailsapp.FormatRequest): Promise<wailsapp.FormatResult>;

export function InstallBinary(arg1: string): Promise<wailsapp.BinActionResult>;

export function InstallRuntime(arg1: string): Promise<wailsapp.BinActionResult>;

export function Run(arg1: wailsapp.RunRequest): Promise<wailsapp.FormatResult>;

export function SaveConfig(arg1: Record<string, any>): Promise<wailsapp.ConfigResult>;

export function UninstallBinary(arg1: string): Promise<wailsapp.BinActionResult>;

export function UpdateLanguage(arg1: Record<string, any>): Promise<wailsapp.ConfigResult>;

export function UpdateRuntime(arg1: Record<string, any>): Promise<wailsapp.ConfigResult>;

export function UpdateTool(arg1: Record<string, any>): Promise<wailsapp.ConfigResult>;

export function VerifyBinary(arg1: string): Promise<wailsapp.BinActionResult>;
